kind = "web"
previewPath = "/"
title = "Sigma Games"
version = "1.0.0"
id = "artifacts/sigma-games"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20158

[services.development]
run = "pnpm --filter @workspace/sigma-games run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/sigma-games", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/sigma-games/dist/server/index.js"]

[services.production.run.env]
PORT = "20158"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/health"

[services.env]
PORT = "20158"
BASE_PATH = "/"
