import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es-mx';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'search.placeholder': 'Search games...',
    'games.all': 'All Games',
    'games.available': 'games available',
    'games.none': 'No games found',
    'games.none.desc': "We couldn't find any games matching \"{query}\" in this category. Try a different search term.",
    'games.loading': 'Loading {title}...',
    'player.open': 'Open in new tab',
    'player.fullscreen': 'Fullscreen',
    'player.close': 'Close game',
    'nav.home': 'Home',
    'nav.games': 'Games',
    'nav.store': 'Store',
    'nav.quests': 'Quests',
    'nav.achievements': 'Achievements',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.inventory': 'Inventory',
    'inventory.title': 'Inventory',
    'inventory.desc': 'Your owned items, skins, and cosmetics.',
    'inventory.empty': 'No Items Yet',
    'inventory.empty.desc': 'Visit the Store to buy items and cosmetics!',
    'inventory.items': 'Owned Items',
    'inventory.skins': 'Snake Skins',
    'inventory.tab.store': 'Store Items',
    'inventory.tab.sigma': 'Sigma Clicker',
    'inventory.login': 'Login Required',
    'inventory.login.desc': 'Log in to view your Sigma Clicker cosmetics.',
    'inventory.sc.empty': 'No Cosmetics Yet',
    'inventory.sc.empty.desc': 'Play Sigma Clicker to unlock badges, titles, and borders!',
    'inventory.sc.unlocked': 'unlocked',
    'inventory.sc.badges': 'Badges',
    'inventory.sc.titles': 'Mastery Titles',
    'inventory.sc.borders': 'Borders',
    'consent.title': 'We value your privacy',
    'consent.desc': 'We use cookies and similar technologies to show you personalized ads, keep our sites running smoothly, and understand how they are used. You can choose to consent to our use of these technologies, manage your own preferences, or decline.',
    'consent.accept': 'Consent',
    'consent.reject': 'Do not consent',
    'consent.manage': 'Manage options',
    'consent.manage.title': 'Manage consent preferences',
    'consent.purpose.ads': 'Personalized advertising',
    'consent.purpose.ads.desc': 'Ads can be shown to you based on the content you are viewing, the app you are using, your approximate location, or your device type.',
    'consent.purpose.analytics': 'Analytics',
    'consent.purpose.analytics.desc': 'Help us understand how visitors interact with our website by collecting and reporting information anonymously.',
    'consent.purpose.functional': 'Functional',
    'consent.purpose.functional.desc': 'Enable enhanced functionality and personalization, such as saving your preferences.',
    'consent.save': 'Save preferences',
    'notif.friend-request': 'sent you a friend request!',
    'notif.friend-online': 'is now online!',
    'notif.achievement': 'Achievement unlocked!',
    'notif.dm': 'sent you a message!',
    'nav.social': 'Social Hub',
    'nav.aichat': 'Vault AI',
    'nav.roadmap': 'Roadmap',
    'nav.daily': 'Daily Rewards',
    'nav.menu': 'Menu',
    'nav.categories': 'Categories',
    'footer.title': 'Unblocked Games',
    'footer.desc': 'Play 48+ games anywhere, anytime.',
    'cat.all': 'All Games',
    'cat.action': 'Action',
    'cat.sandbox': 'Sandbox',
    'cat.clicker': 'Clicker',
    'cat.puzzle': 'Puzzle',
    'cat.sports': 'Sports',
    'cat.io': 'IO Games',
    'cat.iogames': 'IO Games',
    'cat.classics': 'Classics',
    'cat.strategy': 'Strategy',
    'cat.racing': 'Racing',
    'cat.asmr': 'ASMR',
    'cat.papas': "Papa's",
    'cat.fun': 'Fun',
    'cat.adventure': 'Adventure',
    'cat.arcade': 'Arcade',
    'cat.simulation': 'Simulation',
    'store.title': 'Neon Store',
    'store.desc': 'Spend your hard-earned coins on exclusive upgrades.',
    'store.mystery': 'Mystery Boxes',
    'store.snake': 'Snake Skin Box',
    'store.snake.desc': 'Unlock exclusive skins for the Neon Snake game. Guarantees a skin you don\'t already own!',
    'store.open': 'Open for {cost} Coins',
    'store.unlocked': 'Unlocked: {item}',
    'store.cosmetics': 'Cosmetics & Perks',
    'store.owned': 'Owned',
    'store.item.streak-freeze.name': 'Streak Freeze',
    'store.item.streak-freeze.desc': 'Miss a day? Your streak will be saved automatically.',
    'store.item.neon-theme.name': 'Neon Glow Theme',
    'store.item.neon-theme.desc': 'Unlock a premium fuchsia neon glow for all game cards.',
    'store.item.emerald-theme.name': 'Emerald Theme',
    'store.item.emerald-theme.desc': 'Unlock a lush green theme for your profile.',
    'store.item.ruby-theme.name': 'Ruby Theme',
    'store.item.ruby-theme.desc': 'Unlock a deep red theme for your profile.',
    'store.item.golden-crown.name': 'Golden Crown',
    'store.item.golden-crown.desc': 'Show off your wealth with a golden crown next to your streak.',
    'store.item.diamond-crown.name': 'Diamond Crown',
    'store.item.diamond-crown.desc': 'The ultimate flex. A diamond crown for the elite.',
    'store.item.vip-badge.name': 'VIP Badge',
    'store.item.vip-badge.desc': 'Exclusive VIP status icon on your profile.',
    'store.item.glitch-fx.name': 'Glitch FX',
    'store.item.glitch-fx.desc': 'Add a cyberpunk glitch effect to your avatar.',
    'store.item.border-flame.name': 'Flame Border',
    'store.item.border-flame.desc': 'A fiery orange border that blazes around your avatar.',
    'store.item.border-frost.name': 'Frost Border',
    'store.item.border-frost.desc': 'An icy crystalline border for a cool look.',
    'store.item.border-toxic.name': 'Toxic Border',
    'store.item.border-toxic.desc': 'A radioactive green glow around your avatar.',
    'store.item.border-galaxy.name': 'Galaxy Border',
    'store.item.border-galaxy.desc': 'A cosmic purple swirl for your profile picture.',
    'store.item.border-rainbow.name': 'Rainbow Border',
    'store.item.border-rainbow.desc': 'A vibrant rainbow gradient border. Stand out!',
    'store.item.border-legendary.name': 'Legendary Border',
    'store.item.border-legendary.desc': 'The ultimate animated gold legendary frame.',
    'store.item.sigma-2x-boost.name': 'Sigma 2x Click Boost',
    'store.item.sigma-2x-boost.desc': 'Permanently double your click power in Sigma Clicker.',
    'store.item.sigma-auto-clicker.name': 'Sigma Auto-Click Token',
    'store.item.sigma-auto-clicker.desc': 'Permanently grants +10 automatic clicks per second in Sigma Clicker.',
    'store.item.sigma-heat-shield.name': 'Sigma Heat Shield',
    'store.item.sigma-heat-shield.desc': 'Permanently makes overheat cooldown 2% faster in Sigma Clicker.',
    'store.item.sigma-golden-orb.name': 'Golden Orb Skin',
    'store.item.sigma-golden-orb.desc': 'Your Sigma Clicker orb gets a golden glow effect.',
    'store.item.sigma-neon-orb.name': 'Neon Orb Skin',
    'store.item.sigma-neon-orb.desc': 'A cyberpunk neon pink orb skin for Sigma Clicker.',
    'store.item.sigma-island-theme.name': 'Sigma Island Theme',
    'store.item.sigma-island-theme.desc': 'Unlock a custom island theme for your Sigma Clicker beach.',
    'store.equip': 'Equip',
    'store.unequip': 'Unequip',
    'store.active': 'Active',
    'quests.title': 'Quests',
    'quests.desc': 'Complete objectives to earn coins.',
    'quests.daily': 'Daily Quests',
    'quests.weekly': 'Weekly Quests',
    'quests.claimed': 'Claimed',
    'quests.claim': 'Claim Reward',
    'quests.progress': 'In Progress',
    'achievements.title': 'Achievements',
    'achievements.desc': 'Unlock milestones to earn massive coin rewards.',
    'achievements.unlocked': 'UNLOCKED',
    'achievements.claimed': 'CLAIMED',
    'achievements.claim': 'Claim',
    'achievements.locked': 'Locked',
    'ach.first-blood.title': 'First Blood',
    'ach.first-blood.desc': 'Play your first game',
    'ach.gamer.title': 'Gamer',
    'ach.gamer.desc': 'Play 10 games total',
    'ach.addicted.title': 'Addicted',
    'ach.addicted.desc': 'Play 50 games total',
    'ach.master.title': 'Arcade Master',
    'ach.master.desc': 'Play 100 games total',
    'ach.grandmaster.title': 'Grandmaster',
    'ach.grandmaster.desc': 'Play 500 games total',
    'ach.dedicated.title': 'Dedicated',
    'ach.dedicated.desc': 'Reach a 3-day streak',
    'ach.weekly-warrior.title': 'Weekly Warrior',
    'ach.weekly-warrior.desc': 'Reach a 7-day streak',
    'ach.fortnight-fanatic.title': 'Fortnight Fanatic',
    'ach.fortnight-fanatic.desc': 'Reach a 14-day streak',
    'ach.monthly-legend.title': 'Monthly Legend',
    'ach.monthly-legend.desc': 'Reach a 30-day streak',
    'ach.quarterly-king.title': 'Quarterly King',
    'ach.quarterly-king.desc': 'Reach a 90-day streak',
    'ach.sports-fan.title': 'Sports Fan',
    'ach.sports-fan.desc': 'Play 5 Sports games',
    'ach.sports-pro.title': 'Sports Pro',
    'ach.sports-pro.desc': 'Play 15 Sports games',
    'ach.action-novice.title': 'Action Novice',
    'ach.action-novice.desc': 'Play 5 Action games',
    'ach.action-expert.title': 'Action Expert',
    'ach.action-expert.desc': 'Play 25 Action games',
    'ach.puzzle-novice.title': 'Puzzle Novice',
    'ach.puzzle-novice.desc': 'Play 5 Puzzle games',
    'ach.puzzle-expert.title': 'Puzzle Expert',
    'ach.puzzle-expert.desc': 'Play 25 Puzzle games',
    'ach.clicker-novice.title': 'Clicker Novice',
    'ach.clicker-novice.desc': 'Play 3 Clicker games',
    'ach.clicker-addict.title': 'Clicker Addict',
    'ach.clicker-addict.desc': 'Play 10 Clicker games',
    'ach.io-novice.title': 'IO Novice',
    'ach.io-novice.desc': 'Play 5 IO Games',
    'ach.io-pro.title': 'IO Pro',
    'ach.io-pro.desc': 'Play 20 IO Games',
    'ach.chefs-apprentice.title': "Chef's Apprentice",
    'ach.chefs-apprentice.desc': "Play 2 Papa's games",
    'ach.head-chef.title': 'Head Chef',
    'ach.head-chef.desc': "Play all 6 Papa's games",
    'ach.classics-fan.title': 'Classics Fan',
    'ach.classics-fan.desc': 'Play 3 Classics games',
    'ach.sandbox-explorer.title': 'Sandbox Explorer',
    'ach.sandbox-explorer.desc': 'Play a Sandbox game',
    'ach.asmr-addict.title': 'ASMR Addict',
    'ach.asmr-addict.desc': 'Play 2 ASMR games',
    'ach.wealthy.title': 'Wealthy',
    'ach.wealthy.desc': 'Accumulate 1,000 coins',
    'ach.rich.title': 'High Roller',
    'ach.rich.desc': 'Accumulate 5,000 coins',
    'ach.millionaire.title': 'Millionaire',
    'ach.millionaire.desc': 'Accumulate 10,000 coins',
    'ach.collector.title': 'Collector',
    'ach.collector.desc': 'Buy 3 items from the store',
    'ach.hoarder.title': 'Hoarder',
    'ach.hoarder.desc': 'Buy 10 items from the store',
    'ach.sigma-beginner.title': 'Sigma Beginner',
    'ach.sigma-beginner.desc': 'Earn 1,000 lifetime Sigmas',
    'ach.sigma-grinder.title': 'Sigma Grinder',
    'ach.sigma-grinder.desc': 'Earn 100,000 lifetime Sigmas',
    'ach.sigma-lord.title': 'Sigma Lord',
    'ach.sigma-lord.desc': 'Earn 10,000,000 lifetime Sigmas',
    'ach.sigma-god.title': 'Sigma God',
    'ach.sigma-god.desc': 'Earn 1,000,000,000 lifetime Sigmas',
    'ach.sigma-rebirth.title': 'Ego Death',
    'ach.sigma-rebirth.desc': 'Perform your first Rebirth',
    'ach.sigma-rebirths-3.title': 'Triple Ego Death',
    'ach.sigma-rebirths-3.desc': 'Perform 3 Rebirths',
    'ach.sigma-clicks-1k.title': 'Clicker Warrior',
    'ach.sigma-clicks-1k.desc': 'Click the Sigma orb 1,000 times',
    'ach.sigma-clicks-10k.title': 'Clicker Legend',
    'ach.sigma-clicks-10k.desc': 'Click the Sigma orb 10,000 times',
    'level.5.title': 'Novice Explorer',
    'level.10.title': 'Apprentice Gamer',
    'level.25.title': 'Seasoned Veteran',
    'level.50.title': 'Arcade Master',
    'level.75.title': 'Grand Champion',
    'level.100.title': 'Legendary Status',
    'level.200.title': 'Mythic Entity',
    'level.300.title': 'Divine Being',
    'level.400.title': 'Cosmic Overlord',
    'level.500.title': 'Universal Creator',
    'quest.daily-play-3.title': 'Warmup',
    'quest.daily-play-3.desc': 'Play 3 games today',
    'quest.daily-play-10.title': 'Marathon',
    'quest.daily-play-10.desc': 'Play 10 games today',
    'quest.daily-action-2.title': 'Action Hero',
    'quest.daily-action-2.desc': 'Play 2 Action games today',
    'quest.daily-puzzle-2.title': 'Puzzle Master',
    'quest.daily-puzzle-2.desc': 'Play 2 Puzzle games today',
    'quest.daily-sports-2.title': 'Athlete',
    'quest.daily-sports-2.desc': 'Play 2 Sports games today',
    'quest.daily-clicker-1.title': 'Click Frenzy',
    'quest.daily-clicker-1.desc': 'Play 1 Clicker game today',
    'quest.daily-io-2.title': 'Online Warrior',
    'quest.daily-io-2.desc': 'Play 2 IO Games today',
    'quest.daily-papas-1.title': "Papa's Helper",
    'quest.daily-papas-1.desc': "Play a Papa's game today",
    'quest.weekly-play-25.title': 'Weekend Warrior',
    'quest.weekly-play-25.desc': 'Play 25 games this week',
    'quest.weekly-streak-5.title': 'Consistent Gamer',
    'quest.weekly-streak-5.desc': 'Reach a 5-day streak',
    'quest.weekly-action-10.title': 'Action Fanatic',
    'quest.weekly-action-10.desc': 'Play 10 Action games this week',
    'quest.weekly-puzzle-10.title': 'Big Brain',
    'quest.weekly-puzzle-10.desc': 'Play 10 Puzzle games this week',
    'quest.weekly-sports-7.title': 'League MVP',
    'quest.weekly-sports-7.desc': 'Play 7 Sports games this week',
    'quest.weekly-clicker-5.title': 'Clicker Legend',
    'quest.weekly-clicker-5.desc': 'Play 5 Clicker games this week',
    'quest.weekly-io-8.title': 'IO Dominator',
    'quest.weekly-io-8.desc': 'Play 8 IO Games this week',
    'quest.weekly-papas-3.title': "Papa's Regular",
    'quest.weekly-papas-3.desc': "Play 3 Papa's games this week",
    'profile.title': 'Profile',
    'profile.lvl': 'Level',
    'profile.xp': 'XP',
    'profile.streak': 'Current Streak',
    'profile.coins': 'Total Coins',
    'profile.played': 'Games Played',
    'profile.daily': 'Daily Reward',
    'profile.claim': 'Claim Now',
    'profile.claimed': 'Claimed',
    'profile.skins': 'Active Skins',
    'profile.snake': 'Neon Snake',
    'profile.snake.desc': 'Select your equipped skin for the Snake game.',
    'profile.badges': 'Achievement Badges',
    'profile.badges.none': 'No Badges Yet',
    'profile.badges.none.desc': 'Play games and complete achievements to earn badges!',
    'profile.redeem': 'Redeem Code',
    'profile.data': 'Data Management',
    'profile.export': 'Export Save',
    'profile.export.desc': 'Export your save data to keep your progress if you host this website elsewhere.',
    'profile.import': 'Import Save',
    'profile.save': 'Save Profile',
    'profile.edit': 'Edit Profile',
    'profile.prestige': 'Prestige',
    'profile.owner': 'Owner',
    'profile.admin': 'Admin',
    'profile.days': 'Days',
    'profile.multiplier': 'MULTIPLIER',
    'header.lvl': 'LVL',
    'header.coins': 'Coins',
    'header.streak': 'Daily Streak',
    'header.multiplier': 'Multiplier',
    'header.rewards': 'Click for Rewards',
    'header.roadmap': 'Roadmap',
    'header.quests': 'Quests',
    'header.achievements': 'Achievements',
    'header.store': 'Store',
    'header.profile': 'Profile',
    'lang.english': 'English',
    'lang.spanish': 'Español (MX)',
    'roadmap.title': 'Progression Roadmap',
    'roadmap.desc': 'Level up to unlock exclusive rewards and titles.',
    'roadmap.current': 'Current Level',
    'roadmap.next': 'Next Level',
    'roadmap.prestige.avail': 'Prestige Available!',
    'roadmap.prestige.desc': 'Reset your level to 1 and gain a Prestige rank.',
    'roadmap.prestige.confirm': 'Are you sure you want to Prestige? This will reset your level and XP to 1, but you will gain a Prestige rank!',
    'roadmap.prestige.now': 'Prestige Now',
    'roadmap.level': 'Level',
    'roadmap.claim': 'Claim Reward',
    'roadmap.claimed': 'Claimed',
    'roadmap.locked': 'Locked',
    'daily.title': 'Daily Rewards',
    'daily.desc': 'Keep your streak alive to multiply your daily coins!',
    'daily.streak': 'Current Streak',
    'daily.multiplier': 'Current Multiplier',
    'daily.claim': 'Claim Daily Reward',
    'daily.claimed.msg': 'Daily reward claimed!',
    'daily.tomorrow': 'Come back tomorrow!',
    'daily.upcoming': 'Upcoming Rewards',
    'daily.day': 'Day',
    'daily.available': 'Available Now!',
    'sc.tab.upgrades': 'Upgrades',
    'sc.tab.puzzles': 'Brainmaxx',
    'sc.tab.rebirth': 'Rebirth',
    'sc.tab.stats': 'Stats',
    'sc.tab.board': 'Board',
    'sc.tab.credits': 'Credits',
    'sc.clickPower': 'Click Power',
    'sc.idlePower': 'Idle Power',
    'sc.up.mewing.name': 'Mewing Streak',
    'sc.up.mewing.desc': '+1 per click',
    'sc.up.jawline.name': 'Jawline Gum',
    'sc.up.jawline.desc': '+4 per click',
    'sc.up.bonesmash.name': 'Bone Smashing',
    'sc.up.bonesmash.desc': '+12 per click',
    'sc.up.looksmax.name': 'Looksmaxxing Guide',
    'sc.up.looksmax.desc': '+40 per click',
    'sc.up.mogging.name': 'Mogging the Room',
    'sc.up.mogging.desc': '+150 per click',
    'sc.up.sigma-aura.name': 'Sigma Aura Field',
    'sc.up.sigma-aura.desc': '+600 per click',
    'sc.up.reality-warp.name': 'Reality Warp',
    'sc.up.reality-warp.desc': '+2500 per click',
    'sc.up.universe-mog.name': 'Universe Mog',
    'sc.up.universe-mog.desc': '+12000 per click',
    'sc.up.jawline-gum.name': 'Jawline Gum',
    'sc.up.jawline-gum.desc': 'Razor-sharp jaw. +35,000 SPC',
    'sc.up.guasha.name': 'Gua Sha Stone',
    'sc.up.guasha.desc': 'Scraping away the weakness. +100,000 SPC',
    'sc.up.mewing2.name': 'Mewing Streak II',
    'sc.up.mewing2.desc': 'Tongue on the roof. Do not speak. +300,000 SPC',
    'sc.up.hunter-eyes.name': 'Hunter Eyes',
    'sc.up.hunter-eyes.desc': 'Positive canthal tilt achieved. +1M SPC',
    'sc.up.bonesmash2.name': 'Bone Smashing Hammer',
    'sc.up.bonesmash2.desc': 'Extreme measures for extreme results. +3.5M SPC',
    'sc.up.skincare.name': "Dermatologist's Secret",
    'sc.up.skincare.desc': 'Perfect skin reflects your inner Sigma. +12M SPC',
    'sc.up.mogging-aura.name': 'Mogging Aura',
    'sc.up.mogging-aura.desc': "Everyone else's aura drops. +50M SPC",
    'sc.up.golden-ratio.name': 'The Golden Ratio',
    'sc.up.golden-ratio.desc': 'Mathematically perfect symmetry. +250M SPC',
    'sc.up.ego-expansion.name': 'Ego Expansion',
    'sc.up.ego-expansion.desc': 'You are the main character. +1B SPC',
    'sc.up.gym.name': 'Gym Membership',
    'sc.up.gym.desc': '+1 per sec',
    'sc.up.creatine.name': 'Creatine Scoop',
    'sc.up.creatine.desc': '+5 per sec',
    'sc.up.tren.name': 'Trenbologna Sandwiches',
    'sc.up.tren.desc': '+18 per sec',
    'sc.up.sleep.name': 'Sleepmaxxing',
    'sc.up.sleep.desc': '+65 per sec',
    'sc.up.gigachad.name': 'Giga-Chad Mentor',
    'sc.up.gigachad.desc': '+250 per sec',
    'sc.up.sigma-factory.name': 'Sigma Factory',
    'sc.up.sigma-factory.desc': '+1000 per sec',
    'sc.up.enlightenment.name': 'Enlightenment',
    'sc.up.enlightenment.desc': '+5000 per sec',
    'sc.up.transcendence.name': 'Transcendence',
    'sc.up.transcendence.desc': '+25000 per sec',
    'sc.up.protein.name': 'Protein Scoop',
    'sc.up.protein.desc': 'Dry scooping your way to the top. +75,000 CPS',
    'sc.up.raw-egg.name': 'Raw Egg Diet',
    'sc.up.raw-egg.desc': 'Drinking them like Rocky. +200,000 CPS',
    'sc.up.gym2.name': 'Planet Fitness Membership',
    'sc.up.gym2.desc': "It's a start, even with the lunk alarm. +600,000 CPS",
    'sc.up.alarm.name': '4:00 AM Alarm Clock',
    'sc.up.alarm.desc': 'Waking up before the competition sleeps. +2M CPS',
    'sc.up.icebath.name': 'Ice Bath Plunge',
    'sc.up.icebath.desc': 'Freezing the pain, maximizing dopamine. +7M CPS',
    'sc.up.tren2.name': 'Trenbologna Sandwich',
    'sc.up.tren2.desc': 'The forbidden gym snack. Unnatural gains. +25M CPS',
    'sc.up.gigachad2.name': 'Giga-Chad Mentor II',
    'sc.up.gigachad2.desc': 'Training under the legend himself. +100M CPS',
    'sc.up.cryochamber.name': 'Cryotherapy Chamber',
    'sc.up.cryochamber.desc': 'Liquid nitrogen recovery. No more fatigue. +500M CPS',
    'sc.up.podcast.name': 'Podcast Microphone',
    'sc.up.podcast.desc': 'Your grindset reaches millions passively. +2B CPS',
    'sc.heat.overheated': 'OVERHEATED! Cooling down...',
    'sc.heat.hot': 'Getting hot!',
    'sc.heat.label': 'Heat',
    'sc.heat.idle': 'Click the Sigma to earn',
    'sc.brainfog.title': 'Brain Fog!',
    'sc.brainfog.desc': 'Unnatural clicking detected. Regain focus to continue.',
    'sc.loginToSave': 'Log in to save',
    'sc.originates': 'Originates from',
    'sc.scrollMenu': 'Scroll for menu',
    'sc.island.waterpark': 'Water Park',
    'sc.island.upgradeStation': 'Upgrade Station',
    'sc.island.buyUpgrades': 'Buy upgrades to evolve your island',
    'sc.island.balance': 'Balance',
    'sc.island.mystic': 'Mystic Island',
    'sc.island.ancientPowers': 'Ancient Powers',
    'sc.prestige.title': 'Prestige (Ego Death)',
    'sc.prestige.desc': 'Reset everything for a permanent Aura Multiplier boost. First 3 prestiges give huge bonuses!',
    'sc.prestige.required': 'Required',
    'sc.prestige.current': 'Current',
    'sc.prestige.aura': 'Aura',
    'sc.trivia.title': 'Trivia Machine',
    'sc.trivia.desc': 'Answer trivia for Sigma Coins or a 2x multiplier. Wrong = 2 min cooldown.',
    'sc.trivia.recharging': 'Machine recharging...',
    'sc.trivia.generate': 'Generate Trivia Question',
    'sc.puzzles.title': 'Brainmaxxing Puzzles',
    'sc.puzzles.desc': 'Solve puzzles for permanent multipliers. Fail = 5 min cooldown.',
    'sc.rebirth.title': '☠️ Ego Death',
    'sc.rebirth.desc': 'Reset your Sigmas, Upgrades, and Puzzles for +1 Prestige Point and a stronger Aura Multiplier.',
    'sc.stat.rawClicks': 'Raw Clicks',
    'sc.stat.sigmas': 'Sigmas',
    'sc.stat.spc': 'SPC (Per Click)',
    'sc.stat.cps': 'CPS (Idle/sec)',
    'sc.stat.cpm': 'CPM (Your Clicks)',
    'sc.stat.sessionTime': 'Session Time',
    'sc.stat.hoursPlayed': 'Hours Played',
    'sc.stat.upgradesBought': 'Upgrades Bought',
    'sc.stat.rebirths': 'Rebirths',
    'sc.stat.auraMult': 'Aura Multiplier',
    'sc.stat.brainMult': 'Brain Multiplier',
    'sc.stat.lifetimeSigmas': 'Lifetime Sigmas',
    'sc.credits.title': 'Credits & Socials',
    'sc.loading': 'Loading...',
    'sc.hud.click': 'click',
    'sc.hud.sec': 'sec',
    'sc.hud.brain': 'Brain',
    'sc.hud.boost': 'Boost!',
    'sc.island.mysticShort': 'Mystic Isle',
    'sc.prestige.currentAura': 'Current Aura',
    'sc.rebirth.egoBtn': 'Ego Death',
    'sc.puzzle.cancel': 'Cancel',
    'sc.puzzle.active': 'Active',
    'sc.puzzle.attempt': 'Attempt',
    'sc.wp.barren': 'Barren Sandbar',
    'sc.wp.kiddie': 'Kiddie Pool',
    'sc.wp.lazy': 'Lazy River',
    'sc.wp.wave': 'Wave Pool',
    'sc.wp.mega': 'Mega Slide',
    'sc.wp.resort': 'Full Resort',
    'sc.wp.paradise': 'Tropical Paradise',
    'sc.pr.brain2x.name': 'Brain Power 2x',
    'sc.pr.brain2x.desc': '2x all earnings',
    'sc.pr.sigma3x.name': 'Sigma Vision 3x',
    'sc.pr.sigma3x.desc': '3x all earnings',
    'sc.pr.ascend5x.name': 'Ascended Mind 5x',
    'sc.pr.ascend5x.desc': '5x all earnings',
    'sc.mini.watch': 'Watch the sequence...',
    'sc.mini.repeat': 'Repeat it!',
    'sc.mini.wrong': 'Wrong! Brain fog detected...',
    'sc.mini.solved': 'Puzzle solved!',
    'sc.mini.solve': 'Solve this equation:',
    'sc.mini.submit': 'Submit',
    'sc.mini.focus': 'Hit 8 targets to regain focus',
    'sc.lb.title': 'Leaderboard',
    'sc.lb.local': 'Local',
    'sc.lb.friends': 'Friends',
    'sc.lb.global': 'Global',
    'sc.lb.noRuns': 'No runs recorded yet. Keep playing!',
    'sc.lb.shareCode': 'Share your code with friends:',
    'sc.lb.loginFirst': 'Log in first',
    'sc.lb.friendsSoon': 'Friends leaderboard coming soon',
    'sc.lb.loginGlobal': 'Log in to see the global leaderboard',
    'sc.lb.loading': 'Loading...',
    'sc.lb.noEntries': 'No entries yet. Be the first!',
    'sc.lb.you': 'You',
    'sc.patch.title': 'Sigma Clicker Patch Notes',
    'sc.patch.footer': 'Stay sigma. Stay grinding.',
    'sc.patch.v25.title': 'The Social & Badges Update',
    'sc.patch.v25.lb.title': 'Enhanced Leaderboard',
    'sc.patch.v25.lb.desc': 'The global leaderboard now shows player avatars, name colors, borders, and levels. See who\'s really grinding.',
    'sc.patch.v25.badges.title': 'Achievement Badges',
    'sc.patch.v25.badges.desc': 'All 8 Sigma achievements now grant exclusive badges to your profile. Flex your grind.',
    'sc.patch.v25.shop.title': 'Sigma Shop Items',
    'sc.patch.v25.shop.desc': '6 new items in the store: 2x boost, auto-click token, heat shield, golden orb skin, neon orb skin, and island theme.',
    'sc.patch.v25.lang.title': 'Full Spanish Support',
    'sc.patch.v25.lang.desc': 'Sigma Clicker now fully supports Spanish (MX). All upgrades, menus, islands, stats, and patch notes are translated.',
    'sc.patch.v25.quests.title': 'Quest Rotation',
    'sc.patch.v25.quests.desc': 'Daily and weekly quests now rotate — 3 of 8 quests shown each day/week so there\'s always something fresh.',
    'sc.patch.v20.title': 'The Water Park Update',
    'sc.patch.v20.waterpark.title': 'Water Park Island',
    'sc.patch.v20.waterpark.desc': 'The Right Island evolves into a full water park as you buy upgrades! From barren sandbar to tropical paradise.',
    'sc.patch.v20.overheat.title': 'Overheat Mechanic',
    'sc.patch.v20.overheat.desc': 'Click too fast and the orb overheats! A heat meter builds with every click. Max it out for a cooldown period.',
    'sc.patch.v20.mystic.title': 'Mystic Island',
    'sc.patch.v20.mystic.desc': 'The Left Island is now the Mystic Isle! Access your Prestige system and Trivia Machine.',
    'sc.patch.v20.trivia.title': 'Trivia Machine',
    'sc.patch.v20.trivia.desc': '25 handcrafted trivia questions. Answer correctly for Sigma coins or a 2x multiplier. Wrong = 2 min cooldown.',
    'sc.patch.v20.opt.title': 'Optimization',
    'sc.patch.v20.opt.desc': 'Under-the-hood improvements for buttery smooth performance at 60fps.',
    'sc.patch.v20.islands.title': 'Island Interactions',
    'sc.patch.v20.islands.desc': 'Both islands are clickable! Left = Mystic powers. Right = Upgrades & Water Park.',
    'settings.subtitle': 'Manage your preferences',
    'settings.language': 'Language',
    'settings.privacy': 'Privacy',
    'settings.privacy.subtitle': 'Control what other players can see on your profile.',
    'settings.privacy.loading': 'Loading privacy settings...',
    'settings.privacy.hide-inventory': 'Hide Inventory',
    'settings.privacy.hide-inventory.desc': 'Other players cannot see your items',
    'settings.privacy.hide-stats': 'Hide Stats',
    'settings.privacy.hide-stats.desc': 'Hide your coins, XP, and streak from others',
    'settings.privacy.hide-activity': 'Hide Activity',
    'settings.privacy.hide-activity.desc': 'Hide your online status and current game',
  },
  'es-mx': {
    'search.placeholder': 'Buscar juegos...',
    'games.all': 'Todos los Juegos',
    'games.available': 'juegos disponibles',
    'games.none': 'No se encontraron juegos',
    'games.none.desc': "No pudimos encontrar ningún juego que coincida con \"{query}\" en esta categoría. Intenta con otro término de búsqueda.",
    'games.loading': 'Cargando {title}...',
    'player.open': 'Abrir en nueva pestaña',
    'player.fullscreen': 'Pantalla completa',
    'player.close': 'Cerrar juego',
    'nav.home': 'Inicio',
    'nav.games': 'Juegos',
    'nav.store': 'Tienda',
    'nav.quests': 'Misiones',
    'nav.achievements': 'Logros',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.inventory': 'Inventario',
    'inventory.title': 'Inventario',
    'inventory.desc': 'Tus objetos, skins y cosméticos.',
    'inventory.empty': 'Sin Objetos',
    'inventory.empty.desc': '¡Visita la Tienda para comprar objetos y cosméticos!',
    'inventory.items': 'Objetos',
    'inventory.skins': 'Skins de Serpiente',
    'inventory.tab.store': 'Objetos de Tienda',
    'inventory.tab.sigma': 'Sigma Clicker',
    'inventory.login': 'Inicio de Sesion Requerido',
    'inventory.login.desc': 'Inicia sesion para ver tus cosmeticos de Sigma Clicker.',
    'inventory.sc.empty': 'Sin Cosmeticos',
    'inventory.sc.empty.desc': 'Juega Sigma Clicker para desbloquear insignias, titulos y bordes!',
    'inventory.sc.unlocked': 'desbloqueados',
    'inventory.sc.badges': 'Insignias',
    'inventory.sc.titles': 'Titulos de Maestria',
    'inventory.sc.borders': 'Bordes',
    'consent.title': 'Valoramos tu privacidad',
    'consent.desc': 'Usamos cookies y tecnologias similares para mostrarte anuncios personalizados, mantener nuestros sitios funcionando y entender como se usan. Puedes elegir consentir, gestionar tus preferencias o rechazar.',
    'consent.accept': 'Consentir',
    'consent.reject': 'No consentir',
    'consent.manage': 'Gestionar opciones',
    'consent.manage.title': 'Gestionar preferencias de consentimiento',
    'consent.purpose.ads': 'Publicidad personalizada',
    'consent.purpose.ads.desc': 'Los anuncios pueden mostrarse segun el contenido que ves, la app que usas, tu ubicacion aproximada o tu tipo de dispositivo.',
    'consent.purpose.analytics': 'Analitica',
    'consent.purpose.analytics.desc': 'Nos ayuda a entender como los visitantes interactuan con nuestro sitio web.',
    'consent.purpose.functional': 'Funcional',
    'consent.purpose.functional.desc': 'Habilita funcionalidad mejorada y personalizacion, como guardar tus preferencias.',
    'consent.save': 'Guardar preferencias',
    'notif.friend-request': '¡te envió solicitud de amistad!',
    'notif.friend-online': '¡está en línea!',
    'notif.achievement': '¡Logro desbloqueado!',
    'notif.dm': '¡te envió un mensaje!',
    'nav.social': 'Hub Social',
    'nav.aichat': 'Vault IA',
    'nav.roadmap': 'Hoja de Ruta',
    'nav.daily': 'Recompensas Diarias',
    'nav.menu': 'Menú',
    'nav.categories': 'Categorías',
    'footer.title': 'Juegos Desbloqueados',
    'footer.desc': 'Juega más de 48 juegos en cualquier lugar y momento.',
    'cat.all': 'Todos los Juegos',
    'cat.action': 'Acción',
    'cat.sandbox': 'Sandbox',
    'cat.clicker': 'Clicker',
    'cat.puzzle': 'Puzzle',
    'cat.sports': 'Deportes',
    'cat.io': 'Juegos IO',
    'cat.iogames': 'Juegos IO',
    'cat.classics': 'Clásicos',
    'cat.strategy': 'Estrategia',
    'cat.racing': 'Carreras',
    'cat.asmr': 'ASMR',
    'cat.papas': 'Papa',
    'cat.fun': 'Diversión',
    'cat.adventure': 'Aventura',
    'cat.arcade': 'Arcade',
    'cat.simulation': 'Simulación',
    'store.title': 'Tienda Neón',
    'store.desc': 'Gasta tus monedas ganadas con esfuerzo en mejoras exclusivas.',
    'store.mystery': 'Cajas Misteriosas',
    'store.snake': 'Caja de Skins de Snake',
    'store.snake.desc': 'Desbloquea skins exclusivas para el juego Neon Snake. ¡Garantiza una skin que no tengas!',
    'store.open': 'Abrir por {cost} Monedas',
    'store.unlocked': 'Desbloqueado: {item}',
    'store.cosmetics': 'Cosméticos y Ventajas',
    'store.owned': 'Obtenido',
    'store.item.streak-freeze.name': 'Congelador de Racha',
    'store.item.streak-freeze.desc': '¿Perdiste un día? Tu racha se guardará automáticamente.',
    'store.item.neon-theme.name': 'Tema de Brillo Neón',
    'store.item.neon-theme.desc': 'Desbloquea un brillo de neón fucsia premium para todas las tarjetas de juegos.',
    'store.item.emerald-theme.name': 'Tema Esmeralda',
    'store.item.emerald-theme.desc': 'Desbloquea un exuberante tema verde para tu perfil.',
    'store.item.ruby-theme.name': 'Tema Rubí',
    'store.item.ruby-theme.desc': 'Desbloquea un tema rojo intenso para tu perfil.',
    'store.item.golden-crown.name': 'Corona Dorada',
    'store.item.golden-crown.desc': 'Muestra tu riqueza con una corona dorada junto a tu racha.',
    'store.item.diamond-crown.name': 'Corona de Diamante',
    'store.item.diamond-crown.desc': 'La máxima demostración. Una corona de diamante para la élite.',
    'store.item.vip-badge.name': 'Insignia VIP',
    'store.item.vip-badge.desc': 'Icono exclusivo de estado VIP en tu perfil.',
    'store.item.glitch-fx.name': 'Efecto Glitch',
    'store.item.glitch-fx.desc': 'Añade un efecto de falla cyberpunk a tu avatar.',
    'store.item.border-flame.name': 'Borde de Llamas',
    'store.item.border-flame.desc': 'Un borde anaranjado ardiente alrededor de tu avatar.',
    'store.item.border-frost.name': 'Borde de Escarcha',
    'store.item.border-frost.desc': 'Un borde cristalino helado para un look fresco.',
    'store.item.border-toxic.name': 'Borde Tóxico',
    'store.item.border-toxic.desc': 'Un brillo verde radioactivo alrededor de tu avatar.',
    'store.item.border-galaxy.name': 'Borde Galaxia',
    'store.item.border-galaxy.desc': 'Un remolino cósmico púrpura para tu foto de perfil.',
    'store.item.border-rainbow.name': 'Borde Arcoíris',
    'store.item.border-rainbow.desc': 'Un vibrante borde de gradiente arcoíris. ¡Destaca!',
    'store.item.border-legendary.name': 'Borde Legendario',
    'store.item.border-legendary.desc': 'El marco dorado legendario animado definitivo.',
    'store.item.sigma-2x-boost.name': 'Sigma Boost 2x Click',
    'store.item.sigma-2x-boost.desc': 'Duplica permanentemente tu poder de click en Sigma Clicker.',
    'store.item.sigma-auto-clicker.name': 'Token Auto-Click Sigma',
    'store.item.sigma-auto-clicker.desc': 'Otorga permanentemente +10 clicks automáticos por segundo en Sigma Clicker.',
    'store.item.sigma-heat-shield.name': 'Escudo Térmico Sigma',
    'store.item.sigma-heat-shield.desc': 'El enfriamiento por sobrecalentamiento es permanentemente 2% más rápido en Sigma Clicker.',
    'store.item.sigma-golden-orb.name': 'Orbe Dorado',
    'store.item.sigma-golden-orb.desc': 'Tu orbe de Sigma Clicker obtiene un efecto de brillo dorado.',
    'store.item.sigma-neon-orb.name': 'Orbe Neón',
    'store.item.sigma-neon-orb.desc': 'Un orbe de neón rosa cyberpunk para Sigma Clicker.',
    'store.item.sigma-island-theme.name': 'Tema de Isla Sigma',
    'store.item.sigma-island-theme.desc': 'Desbloquea un tema de isla personalizado para tu playa de Sigma Clicker.',
    'store.equip': 'Equipar',
    'store.unequip': 'Desequipar',
    'store.active': 'Activo',
    'quests.title': 'Misiones',
    'quests.desc': 'Completa objetivos para ganar monedas.',
    'quests.daily': 'Misiones Diarias',
    'quests.weekly': 'Misiones Semanales',
    'quests.claimed': 'Reclamado',
    'quests.claim': 'Reclamar Recompensa',
    'quests.progress': 'En Progreso',
    'achievements.title': 'Logros',
    'achievements.desc': 'Desbloquea hitos para ganar recompensas masivas de monedas.',
    'achievements.unlocked': 'DESBLOQUEADO',
    'achievements.claimed': 'RECLAMADO',
    'achievements.claim': 'Reclamar',
    'achievements.locked': 'Bloqueado',
    'ach.first-blood.title': 'Primera Sangre',
    'ach.first-blood.desc': 'Juega tu primer juego',
    'ach.gamer.title': 'Jugador',
    'ach.gamer.desc': 'Juega 10 juegos en total',
    'ach.addicted.title': 'Adicto',
    'ach.addicted.desc': 'Juega 50 juegos en total',
    'ach.master.title': 'Maestro de Arcade',
    'ach.master.desc': 'Juega 100 juegos en total',
    'ach.grandmaster.title': 'Gran Maestro',
    'ach.grandmaster.desc': 'Juega 500 juegos en total',
    'ach.dedicated.title': 'Dedicado',
    'ach.dedicated.desc': 'Alcanza una racha de 3 días',
    'ach.weekly-warrior.title': 'Guerrero Semanal',
    'ach.weekly-warrior.desc': 'Alcanza una racha de 7 días',
    'ach.fortnight-fanatic.title': 'Fanático Quincenal',
    'ach.fortnight-fanatic.desc': 'Alcanza una racha de 14 días',
    'ach.monthly-legend.title': 'Leyenda Mensual',
    'ach.monthly-legend.desc': 'Alcanza una racha de 30 días',
    'ach.quarterly-king.title': 'Rey Trimestral',
    'ach.quarterly-king.desc': 'Alcanza una racha de 90 días',
    'ach.sports-fan.title': 'Fan de Deportes',
    'ach.sports-fan.desc': 'Juega 5 juegos de Deportes',
    'ach.sports-pro.title': 'Profesional Deportivo',
    'ach.sports-pro.desc': 'Juega 15 juegos de Deportes',
    'ach.action-novice.title': 'Novato de Acción',
    'ach.action-novice.desc': 'Juega 5 juegos de Acción',
    'ach.action-expert.title': 'Experto en Acción',
    'ach.action-expert.desc': 'Juega 25 juegos de Acción',
    'ach.puzzle-novice.title': 'Novato en Puzzles',
    'ach.puzzle-novice.desc': 'Juega 5 juegos de Puzzle',
    'ach.puzzle-expert.title': 'Experto en Puzzles',
    'ach.puzzle-expert.desc': 'Juega 25 juegos de Puzzle',
    'ach.clicker-novice.title': 'Novato en Clicker',
    'ach.clicker-novice.desc': 'Juega 3 juegos de Clicker',
    'ach.clicker-addict.title': 'Adicto al Clicker',
    'ach.clicker-addict.desc': 'Juega 10 juegos de Clicker',
    'ach.io-novice.title': 'Novato IO',
    'ach.io-novice.desc': 'Juega 5 Juegos IO',
    'ach.io-pro.title': 'Profesional IO',
    'ach.io-pro.desc': 'Juega 20 Juegos IO',
    'ach.chefs-apprentice.title': 'Aprendiz de Chef',
    'ach.chefs-apprentice.desc': 'Juega 2 juegos de Papa',
    'ach.head-chef.title': 'Chef Principal',
    'ach.head-chef.desc': 'Juega los 6 juegos de Papa',
    'ach.classics-fan.title': 'Fan de Clásicos',
    'ach.classics-fan.desc': 'Juega 3 juegos Clásicos',
    'ach.sandbox-explorer.title': 'Explorador Sandbox',
    'ach.sandbox-explorer.desc': 'Juega un juego Sandbox',
    'ach.asmr-addict.title': 'Adicto al ASMR',
    'ach.asmr-addict.desc': 'Juega 2 juegos ASMR',
    'ach.wealthy.title': 'Adinerado',
    'ach.wealthy.desc': 'Acumula 1,000 monedas',
    'ach.rich.title': 'Gran Apostador',
    'ach.rich.desc': 'Acumula 5,000 monedas',
    'ach.millionaire.title': 'Millonario',
    'ach.millionaire.desc': 'Acumula 10,000 monedas',
    'ach.collector.title': 'Coleccionista',
    'ach.collector.desc': 'Compra 3 artículos de la tienda',
    'ach.hoarder.title': 'Acumulador',
    'ach.hoarder.desc': 'Compra 10 artículos de la tienda',
    'ach.sigma-beginner.title': 'Sigma Principiante',
    'ach.sigma-beginner.desc': 'Gana 1,000 Sigmas de por vida',
    'ach.sigma-grinder.title': 'Sigma Grinder',
    'ach.sigma-grinder.desc': 'Gana 100,000 Sigmas de por vida',
    'ach.sigma-lord.title': 'Sigma Lord',
    'ach.sigma-lord.desc': 'Gana 10,000,000 Sigmas de por vida',
    'ach.sigma-god.title': 'Sigma Dios',
    'ach.sigma-god.desc': 'Gana 1,000,000,000 Sigmas de por vida',
    'ach.sigma-rebirth.title': 'Muerte del Ego',
    'ach.sigma-rebirth.desc': 'Realiza tu primer Renacimiento',
    'ach.sigma-rebirths-3.title': 'Triple Muerte del Ego',
    'ach.sigma-rebirths-3.desc': 'Realiza 3 Renacimientos',
    'ach.sigma-clicks-1k.title': 'Guerrero del Clic',
    'ach.sigma-clicks-1k.desc': 'Haz clic en el orbe Sigma 1,000 veces',
    'ach.sigma-clicks-10k.title': 'Leyenda del Clic',
    'ach.sigma-clicks-10k.desc': 'Haz clic en el orbe Sigma 10,000 veces',
    'level.5.title': 'Explorador Novato',
    'level.10.title': 'Aprendiz de Jugador',
    'level.25.title': 'Veterano Experimentado',
    'level.50.title': 'Maestro de Arcade',
    'level.75.title': 'Gran Campeón',
    'level.100.title': 'Estado Legendario',
    'level.200.title': 'Entidad Mítica',
    'level.300.title': 'Ser Divino',
    'level.400.title': 'Señor Cósmico',
    'level.500.title': 'Creador Universal',
    'quest.daily-play-3.title': 'Calentamiento',
    'quest.daily-play-3.desc': 'Juega 3 juegos hoy',
    'quest.daily-play-10.title': 'Maratón',
    'quest.daily-play-10.desc': 'Juega 10 juegos hoy',
    'quest.daily-action-2.title': 'Héroe de Acción',
    'quest.daily-action-2.desc': 'Juega 2 juegos de Acción hoy',
    'quest.daily-puzzle-2.title': 'Maestro de Puzzles',
    'quest.daily-puzzle-2.desc': 'Juega 2 juegos de Puzzle hoy',
    'quest.daily-sports-2.title': 'Atleta',
    'quest.daily-sports-2.desc': 'Juega 2 juegos de Deportes hoy',
    'quest.daily-clicker-1.title': 'Frenesí de Clics',
    'quest.daily-clicker-1.desc': 'Juega 1 juego de Clicker hoy',
    'quest.daily-io-2.title': 'Guerrero Online',
    'quest.daily-io-2.desc': 'Juega 2 Juegos IO hoy',
    'quest.daily-papas-1.title': 'Ayudante de Papa',
    'quest.daily-papas-1.desc': 'Juega un juego de Papa hoy',
    'quest.weekly-play-25.title': 'Guerrero de Fin de Semana',
    'quest.weekly-play-25.desc': 'Juega 25 juegos esta semana',
    'quest.weekly-streak-5.title': 'Jugador Constante',
    'quest.weekly-streak-5.desc': 'Alcanza una racha de 5 días',
    'quest.weekly-action-10.title': 'Fanático de Acción',
    'quest.weekly-action-10.desc': 'Juega 10 juegos de Acción esta semana',
    'quest.weekly-puzzle-10.title': 'Cerebro Grande',
    'quest.weekly-puzzle-10.desc': 'Juega 10 juegos de Puzzle esta semana',
    'quest.weekly-sports-7.title': 'MVP de la Liga',
    'quest.weekly-sports-7.desc': 'Juega 7 juegos de Deportes esta semana',
    'quest.weekly-clicker-5.title': 'Leyenda del Clicker',
    'quest.weekly-clicker-5.desc': 'Juega 5 juegos de Clicker esta semana',
    'quest.weekly-io-8.title': 'Dominador IO',
    'quest.weekly-io-8.desc': 'Juega 8 Juegos IO esta semana',
    'quest.weekly-papas-3.title': 'Cliente de Papa',
    'quest.weekly-papas-3.desc': 'Juega 3 juegos de Papa esta semana',
    'profile.title': 'Perfil',
    'profile.lvl': 'Nivel',
    'profile.xp': 'XP',
    'profile.streak': 'Racha Actual',
    'profile.coins': 'Monedas Totales',
    'profile.played': 'Juegos Jugados',
    'profile.daily': 'Recompensa Diaria',
    'profile.claim': 'Reclamar Ahora',
    'profile.claimed': 'Reclamado',
    'profile.skins': 'Skins Activas',
    'profile.snake': 'Neon Snake',
    'profile.snake.desc': 'Selecciona tu skin equipada para el juego Snake.',
    'profile.badges': 'Insignias de Logros',
    'profile.badges.none': 'Sin Insignias Aún',
    'profile.badges.none.desc': '¡Juega juegos y completa logros para ganar insignias!',
    'profile.redeem': 'Canjear Código',
    'profile.data': 'Gestión de Datos',
    'profile.export': 'Exportar Partida',
    'profile.export.desc': 'Exporta tus datos guardados para mantener tu progreso si alojas este sitio web en otro lugar.',
    'profile.import': 'Importar Partida',
    'profile.save': 'Guardar Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.prestige': 'Prestigio',
    'profile.owner': 'Dueño',
    'profile.admin': 'Admin',
    'profile.days': 'Días',
    'profile.multiplier': 'MULTIPLICADOR',
    'header.lvl': 'NIVEL',
    'header.coins': 'Monedas',
    'header.streak': 'Racha Diaria',
    'header.multiplier': 'Multiplicador',
    'header.rewards': 'Click para Recompensas',
    'header.roadmap': 'Hoja de Ruta',
    'header.quests': 'Misiones',
    'header.achievements': 'Logros',
    'header.store': 'Tienda',
    'header.profile': 'Perfil',
    'lang.english': 'English',
    'lang.spanish': 'Español (MX)',
    'roadmap.title': 'Hoja de Ruta de Progresión',
    'roadmap.desc': 'Sube de nivel para desbloquear recompensas y títulos exclusivos.',
    'roadmap.current': 'Nivel Actual',
    'roadmap.next': 'Siguiente Nivel',
    'roadmap.prestige.avail': '¡Prestigio Disponible!',
    'roadmap.prestige.desc': 'Reinicia tu nivel a 1 y gana un rango de Prestigio.',
    'roadmap.prestige.confirm': '¿Estás seguro de que quieres hacer Prestigio? ¡Esto reiniciará tu nivel y XP a 1, pero ganarás un rango de Prestigio!',
    'roadmap.prestige.now': 'Prestigio Ahora',
    'roadmap.level': 'Nivel',
    'roadmap.claim': 'Reclamar Recompensa',
    'roadmap.claimed': 'Reclamado',
    'roadmap.locked': 'Bloqueado',
    'daily.title': 'Recompensas Diarias',
    'daily.desc': '¡Mantén tu racha viva para multiplicar tus monedas diarias!',
    'daily.streak': 'Racha Actual',
    'daily.multiplier': 'Multiplicador Actual',
    'daily.claim': 'Reclamar Recompensa Diaria',
    'daily.claimed.msg': '¡Recompensa diaria reclamada!',
    'daily.tomorrow': '¡Vuelve mañana!',
    'daily.upcoming': 'Próximas Recompensas',
    'daily.day': 'Día',
    'daily.available': '¡Disponible Ahora!',
    'sc.tab.upgrades': 'Mejoras',
    'sc.tab.puzzles': 'Cerebromaxx',
    'sc.tab.rebirth': 'Renacimiento',
    'sc.tab.stats': 'Estadísticas',
    'sc.tab.board': 'Tabla',
    'sc.tab.credits': 'Créditos',
    'sc.clickPower': 'Poder de Clic',
    'sc.idlePower': 'Poder Pasivo',
    'sc.up.mewing.name': 'Racha de Mewing',
    'sc.up.mewing.desc': '+1 por clic',
    'sc.up.jawline.name': 'Chicle de Mandíbula',
    'sc.up.jawline.desc': '+4 por clic',
    'sc.up.bonesmash.name': 'Golpe de Huesos',
    'sc.up.bonesmash.desc': '+12 por clic',
    'sc.up.looksmax.name': 'Guía de Looksmaxxing',
    'sc.up.looksmax.desc': '+40 por clic',
    'sc.up.mogging.name': 'Mogging Total',
    'sc.up.mogging.desc': '+150 por clic',
    'sc.up.sigma-aura.name': 'Campo de Aura Sigma',
    'sc.up.sigma-aura.desc': '+600 por clic',
    'sc.up.reality-warp.name': 'Distorsión de Realidad',
    'sc.up.reality-warp.desc': '+2500 por clic',
    'sc.up.universe-mog.name': 'Mog Universal',
    'sc.up.universe-mog.desc': '+12000 por clic',
    'sc.up.jawline-gum.name': 'Chicle de Mandíbula II',
    'sc.up.jawline-gum.desc': 'Mandíbula afilada. +35,000 SPC',
    'sc.up.guasha.name': 'Piedra Gua Sha',
    'sc.up.guasha.desc': 'Raspando la debilidad. +100,000 SPC',
    'sc.up.mewing2.name': 'Racha de Mewing II',
    'sc.up.mewing2.desc': 'Lengua en el paladar. No hables. +300,000 SPC',
    'sc.up.hunter-eyes.name': 'Ojos de Cazador',
    'sc.up.hunter-eyes.desc': 'Inclinación cantal positiva lograda. +1M SPC',
    'sc.up.bonesmash2.name': 'Martillo Rompehuesos',
    'sc.up.bonesmash2.desc': 'Medidas extremas para resultados extremos. +3.5M SPC',
    'sc.up.skincare.name': 'Secreto del Dermatólogo',
    'sc.up.skincare.desc': 'La piel perfecta refleja tu Sigma interior. +12M SPC',
    'sc.up.mogging-aura.name': 'Aura de Mogging',
    'sc.up.mogging-aura.desc': 'El aura de todos los demás cae. +50M SPC',
    'sc.up.golden-ratio.name': 'La Proporción Áurea',
    'sc.up.golden-ratio.desc': 'Simetría matemáticamente perfecta. +250M SPC',
    'sc.up.ego-expansion.name': 'Expansión del Ego',
    'sc.up.ego-expansion.desc': 'Tú eres el protagonista. +1B SPC',
    'sc.up.gym.name': 'Membresía del Gym',
    'sc.up.gym.desc': '+1 por seg',
    'sc.up.creatine.name': 'Cucharada de Creatina',
    'sc.up.creatine.desc': '+5 por seg',
    'sc.up.tren.name': 'Sándwiches de Trembolona',
    'sc.up.tren.desc': '+18 por seg',
    'sc.up.sleep.name': 'Dormirmaxxing',
    'sc.up.sleep.desc': '+65 por seg',
    'sc.up.gigachad.name': 'Mentor Giga-Chad',
    'sc.up.gigachad.desc': '+250 por seg',
    'sc.up.sigma-factory.name': 'Fábrica Sigma',
    'sc.up.sigma-factory.desc': '+1000 por seg',
    'sc.up.enlightenment.name': 'Iluminación',
    'sc.up.enlightenment.desc': '+5000 por seg',
    'sc.up.transcendence.name': 'Trascendencia',
    'sc.up.transcendence.desc': '+25000 por seg',
    'sc.up.protein.name': 'Cucharada de Proteína',
    'sc.up.protein.desc': 'Scooping seco hacia la cima. +75,000 CPS',
    'sc.up.raw-egg.name': 'Dieta de Huevo Crudo',
    'sc.up.raw-egg.desc': 'Bebiéndolos como Rocky. +200,000 CPS',
    'sc.up.gym2.name': 'Membresía Planet Fitness',
    'sc.up.gym2.desc': 'Es un comienzo, incluso con la alarma. +600,000 CPS',
    'sc.up.alarm.name': 'Alarma de las 4:00 AM',
    'sc.up.alarm.desc': 'Despertando antes de que la competencia duerma. +2M CPS',
    'sc.up.icebath.name': 'Baño de Hielo',
    'sc.up.icebath.desc': 'Congelando el dolor, maximizando dopamina. +7M CPS',
    'sc.up.tren2.name': 'Sándwich de Trembolona',
    'sc.up.tren2.desc': 'El snack prohibido del gym. +25M CPS',
    'sc.up.gigachad2.name': 'Mentor Giga-Chad II',
    'sc.up.gigachad2.desc': 'Entrenando bajo la leyenda misma. +100M CPS',
    'sc.up.cryochamber.name': 'Cámara de Crioterapia',
    'sc.up.cryochamber.desc': 'Recuperación con nitrógeno líquido. Sin fatiga. +500M CPS',
    'sc.up.podcast.name': 'Micrófono de Podcast',
    'sc.up.podcast.desc': 'Tu grindset llega a millones pasivamente. +2B CPS',
    'sc.heat.overheated': '¡SOBRECALENTADO! Enfriando...',
    'sc.heat.hot': '¡Se está calentando!',
    'sc.heat.label': 'Calor',
    'sc.heat.idle': 'Haz clic en el Sigma para ganar',
    'sc.brainfog.title': '¡Niebla Mental!',
    'sc.brainfog.desc': 'Clics antinaturales detectados. Recupera el enfoque para continuar.',
    'sc.loginToSave': 'Inicia sesión para guardar',
    'sc.originates': 'Originado de',
    'sc.scrollMenu': 'Desplaza para el menú',
    'sc.island.waterpark': 'Parque Acuático',
    'sc.island.upgradeStation': 'Estación de Mejoras',
    'sc.island.buyUpgrades': 'Compra mejoras para evolucionar tu isla',
    'sc.island.balance': 'Saldo',
    'sc.island.mystic': 'Isla Mística',
    'sc.island.ancientPowers': 'Poderes Ancestrales',
    'sc.prestige.title': 'Prestigio (Muerte del Ego)',
    'sc.prestige.desc': '¡Reinicia todo por un impulso permanente del Multiplicador de Aura! Los primeros 3 prestigios dan bonificaciones enormes.',
    'sc.prestige.required': 'Requerido',
    'sc.prestige.current': 'Actual',
    'sc.prestige.aura': 'Aura',
    'sc.trivia.title': 'Máquina de Trivia',
    'sc.trivia.desc': 'Responde trivia por Monedas Sigma o un multiplicador 2x. Error = 2 min de espera.',
    'sc.trivia.recharging': 'Máquina recargando...',
    'sc.trivia.generate': 'Generar Pregunta de Trivia',
    'sc.puzzles.title': 'Puzzles Cerebromaxx',
    'sc.puzzles.desc': 'Resuelve puzzles para multiplicadores permanentes. Fallo = 5 min de espera.',
    'sc.rebirth.title': '☠️ Muerte del Ego',
    'sc.rebirth.desc': 'Reinicia tus Sigmas, Mejoras y Puzzles por +1 Punto de Prestigio y un multiplicador de Aura más fuerte.',
    'sc.stat.rawClicks': 'Clics Totales',
    'sc.stat.sigmas': 'Sigmas',
    'sc.stat.spc': 'SPC (Por Clic)',
    'sc.stat.cps': 'CPS (Pasivo/seg)',
    'sc.stat.cpm': 'CPM (Tus Clics)',
    'sc.stat.sessionTime': 'Tiempo de Sesión',
    'sc.stat.hoursPlayed': 'Horas Jugadas',
    'sc.stat.upgradesBought': 'Mejoras Compradas',
    'sc.stat.rebirths': 'Renacimientos',
    'sc.stat.auraMult': 'Multiplicador de Aura',
    'sc.stat.brainMult': 'Multiplicador Mental',
    'sc.stat.lifetimeSigmas': 'Sigmas Totales',
    'sc.credits.title': 'Créditos y Redes',
    'sc.loading': 'Cargando...',
    'sc.hud.click': 'clic',
    'sc.hud.sec': 'seg',
    'sc.hud.brain': 'Cerebro',
    'sc.hud.boost': '¡Impulso!',
    'sc.island.mysticShort': 'Isla Mística',
    'sc.prestige.currentAura': 'Aura Actual',
    'sc.rebirth.egoBtn': 'Muerte del Ego',
    'sc.puzzle.cancel': 'Cancelar',
    'sc.puzzle.active': 'Activo',
    'sc.puzzle.attempt': 'Intentar',
    'sc.wp.barren': 'Banco de Arena',
    'sc.wp.kiddie': 'Piscina Infantil',
    'sc.wp.lazy': 'Río Perezoso',
    'sc.wp.wave': 'Piscina de Olas',
    'sc.wp.mega': 'Mega Tobogán',
    'sc.wp.resort': 'Resort Completo',
    'sc.wp.paradise': 'Paraíso Tropical',
    'sc.pr.brain2x.name': 'Poder Mental 2x',
    'sc.pr.brain2x.desc': '2x todas las ganancias',
    'sc.pr.sigma3x.name': 'Visión Sigma 3x',
    'sc.pr.sigma3x.desc': '3x todas las ganancias',
    'sc.pr.ascend5x.name': 'Mente Ascendida 5x',
    'sc.pr.ascend5x.desc': '5x todas las ganancias',
    'sc.mini.watch': 'Observa la secuencia...',
    'sc.mini.repeat': '¡Repítela!',
    'sc.mini.wrong': '¡Error! Niebla mental detectada...',
    'sc.mini.solved': '¡Puzzle resuelto!',
    'sc.mini.solve': 'Resuelve esta ecuación:',
    'sc.mini.submit': 'Enviar',
    'sc.mini.focus': 'Golpea 8 objetivos para recuperar el enfoque',
    'sc.lb.title': 'Tabla de Líderes',
    'sc.lb.local': 'Local',
    'sc.lb.friends': 'Amigos',
    'sc.lb.global': 'Global',
    'sc.lb.noRuns': '¡No hay partidas registradas aún. Sigue jugando!',
    'sc.lb.shareCode': 'Comparte tu código con amigos:',
    'sc.lb.loginFirst': 'Inicia sesión primero',
    'sc.lb.friendsSoon': 'Tabla de amigos próximamente',
    'sc.lb.loginGlobal': 'Inicia sesión para ver la tabla global',
    'sc.lb.loading': 'Cargando...',
    'sc.lb.noEntries': '¡No hay entradas aún. Sé el primero!',
    'sc.lb.you': 'Tú',
    'sc.patch.title': 'Notas de Parche de Sigma Clicker',
    'sc.patch.footer': 'Mantente sigma. Sigue la grindea.',
    'sc.patch.v25.title': 'La Actualización Social y de Insignias',
    'sc.patch.v25.lb.title': 'Tabla de Líderes Mejorada',
    'sc.patch.v25.lb.desc': 'La tabla global ahora muestra avatares, colores de nombre, bordes y niveles. Mira quién realmente está grindeando.',
    'sc.patch.v25.badges.title': 'Insignias de Logro',
    'sc.patch.v25.badges.desc': 'Los 8 logros Sigma ahora otorgan insignias exclusivas a tu perfil. Presume tu grindeo.',
    'sc.patch.v25.shop.title': 'Artículos de la Tienda Sigma',
    'sc.patch.v25.shop.desc': '6 nuevos artículos en la tienda: boost 2x, token de auto-clic, escudo de calor, skin de orbe dorado, skin de orbe neón, y tema de isla.',
    'sc.patch.v25.lang.title': 'Soporte Completo en Español',
    'sc.patch.v25.lang.desc': 'Sigma Clicker ahora soporta completamente Español (MX). Todas las mejoras, menús, islas, estadísticas y notas de parche están traducidos.',
    'sc.patch.v25.quests.title': 'Rotación de Misiones',
    'sc.patch.v25.quests.desc': 'Las misiones diarias y semanales ahora rotan — 3 de 8 misiones mostradas cada día/semana para que siempre haya algo fresco.',
    'sc.patch.v20.title': 'La Actualización del Parque Acuático',
    'sc.patch.v20.waterpark.title': 'Isla del Parque Acuático',
    'sc.patch.v20.waterpark.desc': '¡La Isla Derecha evoluciona en un parque acuático completo mientras compras mejoras! De banco de arena a paraíso tropical.',
    'sc.patch.v20.overheat.title': 'Mecánica de Sobrecalentamiento',
    'sc.patch.v20.overheat.desc': '¡Haz clic demasiado rápido y el orbe se sobrecalienta! Un medidor de calor sube con cada clic. Al máximo, período de enfriamiento.',
    'sc.patch.v20.mystic.title': 'Isla Mística',
    'sc.patch.v20.mystic.desc': '¡La Isla Izquierda ahora es la Isla Mística! Accede a tu sistema de Prestigio y Máquina de Trivia.',
    'sc.patch.v20.trivia.title': 'Máquina de Trivia',
    'sc.patch.v20.trivia.desc': '25 preguntas de trivia artesanales. Responde correctamente por monedas Sigma o un multiplicador 2x. Error = 2 min de espera.',
    'sc.patch.v20.opt.title': 'Optimización',
    'sc.patch.v20.opt.desc': 'Mejoras internas para un rendimiento suave a 60fps.',
    'sc.patch.v20.islands.title': 'Interacciones de Islas',
    'sc.patch.v20.islands.desc': '¡Ambas islas son clickeables! Izquierda = Poderes Místicos. Derecha = Mejoras y Parque Acuático.',
    'settings.subtitle': 'Administra tus preferencias',
    'settings.language': 'Idioma',
    'settings.privacy': 'Privacidad',
    'settings.privacy.subtitle': 'Controla lo que otros jugadores pueden ver en tu perfil.',
    'settings.privacy.loading': 'Cargando configuración de privacidad...',
    'settings.privacy.hide-inventory': 'Ocultar Inventario',
    'settings.privacy.hide-inventory.desc': 'Otros jugadores no podrán ver tus objetos',
    'settings.privacy.hide-stats': 'Ocultar Estadísticas',
    'settings.privacy.hide-stats.desc': 'Oculta tus monedas, XP y racha a los demás',
    'settings.privacy.hide-activity': 'Ocultar Actividad',
    'settings.privacy.hide-activity.desc': 'Oculta tu estado en línea y el juego actual',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('vault_language');
      if (saved === 'en' || saved === 'es-mx') return saved;
    } catch {}
    return 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    try { localStorage.setItem('vault_language', lang); } catch {}
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
